name: CI

on:
    push:
        branches:
            master
    pull_request:
        branches:
            - "*"

jobs:
    test:
        name: Test code

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js Stable version
              uses: actions/setup-node@v1
              width:
                node-version: stable

            - name: Install, test
              run: |
                npm install
                npm run cover
              env:
                CI: true

    lint:
        name: Linting code

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js Stable version
              use: actions/setup-node@v1
              width:
                node-version: stable
            - name: Install, lint
              run: |
                npm install
                npm run lint
              env:
                CI: true
